apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: ks-controller-manager
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/vendor: kubesphere
  name: ks-controller-manager
  namespace: klc-monitoring-system
spec:
  endpoints:
  - interval: 1m
    path: /kapis/metrics
    relabelings:
    - action: labeldrop
      regex: (endpoint)
    targetPort: 8080
  namespaceSelector:
    matchNames:
    - klc-system
  selector:
    matchLabels:
      app: ks-controller-manager
