- name: ceph-csi-rbd | 获取网卡名称
  shell: "ip a|grep '{{ inventory_hostname }}/'|awk '{print $NF}'"
  register: net_card_name

- name: 记录网卡名称
  set_fact:
    api_interface: "{{ net_card_name.stdout }}"

- name: 获取ceph_fs ID
  shell: ceph fs ls -f json | jq '.[].name'
  register: ceph_fs_id

- name: 记录 ceph_fs 名称
  set_fact: 
    ceph_fs_name: "{{ ceph_fs_id.stdout }}"
