- name: harbor | create harbor auth
  shell: echo -n "admin:{{ harbor_local_password }}" | base64  
  register: auth

- name: harbor | create harbor dockerconfigjson
  shell: echo -n '{"auths":{"http://{{ hostvars[groups["harbor"][0]]["ansible_" + hostvars[groups["harbor"][0]]["api_interface"]]["ipv4"]["address"] }}:30002":{"username":"admin","password":"{{ harbor_local_password }}","email":"","auth":"{{ auth.stdout }}"}}}' | base64 -i -w 0
  register: docker_config_base64

- set_fact:
    dockerconfigjson: "{{docker_config_base64.stdout}}"

- name: harbor | create harbor create.yml
  template:
    src: harbor-secret.yaml.j2
    dest: /etc/kubernetes/plugins/harbor/harbor-secret.yaml
    owner: root
    mode: 0644

- name: harbor | create secret
  shell: kubectl apply -f /etc/kubernetes/plugins/harbor/harbor-secret.yaml
