---
- name: Add stable chart repo
  kubernetes.core.helm_repository:
    name: harbor-chart-repo
    repo_username: "{{ harbor_local_username }}"
    repo_password: "{{ harbor_local_password }}"
    repo_url: "http://{{ harbor_local_address }}:30002/chartrepo/library"

- name: Find local chart
  command: "ls {{harbor_local_charts_dir}}"
  register: dir_out

- name: Push chart to harbor
  shell: "helm cm-push {{harbor_local_charts_dir}}/{{ item }} harbor-chart-repo"
  with_items: "{{ dir_out.stdout_lines }}"