---
- name: Docker Login
  docker_login:
    registry: "{{ hostvars[groups['harbor'][0]]['ansible_' + hostvars[groups['harbor'][0]]['api_interface']]['ipv4']['address'] }}:30002"
    username: "{{ harbor_local_username }}"
    debug: true
    password: "{{ harbor_local_password }}"

- name: Add tag to harbor image
  community.docker.docker_image:
    name: "{{ kube_image_repository }}/{{ item }}:{{ harbor_local_chart_image_version }}"  
    repository: "{{ hostvars[groups['harbor'][0]]['ansible_' + hostvars[groups['harbor'][0]]['api_interface']]['ipv4']['address'] }}:30002/library/{{ item }}:arm" 
    force_tag: yes 
    push: true
    source: local
  with_items: 
    - prmp-web-arm
    - prmp-arm
    - mysql
    - redis
    - kubernetes-entrypoint

- name: Remove image
  community.docker.docker_image:
    state: absent
    name: "{{ kube_image_repository }}/{{ item }}:{{ harbor_local_chart_image_version }}" 
    tag: v1
  with_items:
    - prmp-web-arm
    - prmp-arm
    - mysql
    - redis
    - kubernetes-entrypoint
