---
- import_tasks: redis-install.yaml
  run_once: true
  when:
    - common.redis.enabled | bool
  delegate_to: "{{ groups['kube-master'][0] }}"

- import_tasks: openldap-install.yaml
  run_once: true
  when:
    - common.openldap is defined and common.openldap.enabled is defined and common.openldap.enabled
  delegate_to: "{{ groups['kube-master'][0] }}"

- import_tasks: minio-install.yaml
  run_once: true
  when:
    - openpitrix.store is defined and openpitrix.store.enabled is defined and openpitrix.store.enabled and common.s3 is not defined
  delegate_to: "{{ groups['kube-master'][0] }}"
