---
- name: KubeSphere | Labeling system-workspace
  shell: kubectl label ns {{ item }} kubesphere.io/workspace=system-workspace
  register: label_state
  failed_when: "label_state.stderr and 'already' not in label_state.stderr"
  loop: "{{ ['default', 'kube-public', 'kube-system'] | flatten(1) }}"


- name: KubeSphere | Labeling namespace for network policy
  shell: >
    for ns in `kubectl get ns -o jsonpath="{.items[*].metadata.name}"`; do kubectl label  ns $ns kubesphere.io/namespace=$ns --overwrite; done
  failed_when: false
