- name: KubeSphere | Getting minio installation files
  copy:
    src: "{{ item }}"
    dest: "{{ helm_charts_dir }}/"
  loop:
    - "minio-ha"

- name: KubeSphere | Creating manifests
  template:
    src: "custom-values-minio.yaml.j2"
    dest: "/etc/kubernetes/plugins/common/custom-values-minio.yaml"

- name: KubeSphere | Deploying minio
  shell: >
    helm upgrade --install ks-minio
    {{ helm_charts_dir }}/minio-ha
    -f /etc/kubernetes/plugins/common/custom-values-minio.yaml
    --set fullnameOverride=minio
    --namespace default
    --wait --timeout 1800s
  register: minio_status
  failed_when: false

- name: KubeSphere | Importing minio status
  shell: >
    kubectl patch cc ks-installer
    --type merge
    -p '{"status": {"minio": {"status": "enabled", "enabledTime": "{{ lookup('pipe','date  +%Y-%m-%dT%H:%M:%S%Z') }}"}}}'
    -n default
  register: cc_result
  failed_when: "cc_result.stderr and 'Warning' not in cc_result.stderr"
  until: cc_result is succeeded
  retries: 5
  delay: 3
