- name: KubeSphere | Init Redis password
  block:
    - name: KubeSphere | Generet Random password
      set_fact:
        redis_password: "{{ lookup('password', '/dev/null length=15 chars=ascii_letters') }}"
    - name: KubeSphere | Creating Redis Password Secret
      shell: >
        kubectl -n default create secret generic redis-secret --from-literal=auth={{redis_password}}
      register: secret
      failed_when: "secret.stderr and 'already exists' not in secret.stderr"

- name: KubeSphere | Deploying ha redis
  block:

    - name: KubeSphere | Getting redis installation files
      copy:
        src: "{{ item }}"
        dest: "{{ helm_charts_dir }}/"
      loop:
        - "redis-ha"


    - name: KubeSphere | Creating manifests
      template:
        src: "{{ item.file }}.j2"
        dest: "{{ helm_charts_dir }}/{{ item.file }}"
      with_items:
        - { name: custom-values-redis, file: custom-values-redis.yaml }


    - name: KubeSphere | Checking old redis status
      shell: >
        kubectl get pod -n default  -l app=redis,tier=database,version=redis-4.0 | wc -l
      register: old_redis_exist


    - name: KubeSphere | Deleting and backup old redis svc
      shell: >
        kubectl get svc -n default redis -o yaml > {{ helm_charts_dir }}/redis-svc-backup.yaml
        &&
        kubectl delete svc -n default redis
      when:
        - old_redis_exist.stdout != "0"


    - name: KubeSphere | Deploying redis
      shell: >
        helm upgrade --install ks-redis
        {{ helm_charts_dir }}/redis-ha
        -f {{ helm_charts_dir }}/custom-values-redis.yaml
        --set fullnameOverride=redis-ha
        --namespace default

  when:
    - common.redis.enableHA is defined and common.redis.enableHA


- name: KubeSphere | Deploying redis
  shell: >
    kubectl -n default apply -f {{ helm_charts_dir }}/common/{{ item }}
  loop:
    - "redis.yaml"
  register: redis_result
  failed_when:
    - "redis_result.stderr and 'bound claims' not in redis_result.stderr"
    - "redis_result.stderr and 'is forbidden' not in redis_result.stderr"
  when:
    - (common.redis.enableHA is defined and not common.redis.enableHA) or (common.redis.enableHA is not defined)
