apiVersion: v1
kind: Service
metadata:
  name: openebs-lvm-node-service
  namespace: {{ .Release.Namespace }}
  labels:
    name: openebs-lvm-node
spec:
  clusterIP: None
  ports:
    - name: metrics
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    app: openebs-lvm-node