---
- name: 创建 prometheus values 目录
  file:
    name: /etc/kubernetes/plugins/prometheus
    state: directory

- name: Monitoring | Getting ks-monitoring installation files
  copy:
    src: "{{ item }}"
    dest: "{{ helm_charts_dir }}/"
  loop:
    - "prometheus"

- name: Monitoring | Creating manifests
  template:
    src: "{{ item.file }}.j2"
    dest: "/etc/kubernetes/plugins/prometheus/{{ item.file }}"
  with_items:
    - { file: prometheus-operator-deployment.yaml }
    - { file: prometheus-prometheus.yaml }
    - { file: kube-state-metrics-deployment.yaml }
    - { file: node-exporter-daemonset.yaml }
    - { file: alertmanager-alertmanager.yaml }
