---
- name: 创建 notification-manager values 目录
  file:
    name: /etc/kubernetes/plugins/notification-manager
    state: directory

- name: notification-manager | Create notification-manager installation files
  copy:
    src: "notification-manager"
    dest: "{{ helm_charts_dir }}/"

- name: notification-manager | Create notification-manager template files
  template:
    src: "custom-values-notification.yaml.j2"
    dest: "/etc/kubernetes/plugins/notification-manager/custom-values-notification.yaml"

- name: notification-manager | Update notification-manager crds
  shell: kubectl apply -f {{ helm_charts_dir }}/notification-manager/crds/
  register: update_crds
  failed_when: update_crds is not succeeded

- name: notification-manager | Deploying notification-manager
  shell: helm upgrade --install notification-manager
    {{ helm_charts_dir }}/notification-manager
    -f /etc/kubernetes/plugins/notification-manager/custom-values-notification.yaml
    -n {{ helm_install_namespace }}
    --force
  register: deploy_result
  until: deploy_result is succeeded
  retries: 3
  delay: 10