---
- name: Monitoring | Initing prometheus-operator (crds)
  shell: >
    kubectl apply -f {{ helm_charts_dir }}/prometheus/prometheus-operator/*CustomResourceDefinition.yaml || 
    kubectl apply -f {{ helm_charts_dir }}/prometheus/prometheus-operator/*CustomResourceDefinition.yaml --force-conflicts --server-side || 
    kubectl replace -f {{ helm_charts_dir }}/prometheus/prometheus-operator/*CustomResourceDefinition.yaml
  register: prom_result
  failed_when: "prom_result.stderr and 'Warning' not in prom_result.stderr and 'spec.clusterIP' not in prom_result.stderr"
  until: prom_result is succeeded
  retries: 5
  delay: 3

- name: Monitoring | Initing prometheus-operator (resources)
  shell: "kubectl apply -f {{ helm_charts_dir }}/prometheus/prometheus-operator/*.yaml --force || kubectl apply -f {{ helm_charts_dir }}/prometheus/prometheus-operator/*.yaml --force-conflicts --server-side"
  register: prom_result
  failed_when: "prom_result.stderr and 'Warning' not in prom_result.stderr and 'spec.clusterIP' not in prom_result.stderr"
  until: prom_result is succeeded
  retries: 5
  delay: 3
