annotations:
  app.kubesphere.io/category: Database & Cache
apiVersion: v1
appVersion: 6.0.9
description: Redis is an open source (BSD licensed), in-memory data structure store,
  used as a database, cache and message broker.
icon: https://upload.wikimedia.org/wikipedia/en/6/6b/Redis_Logo.svg
maintainers:
- email: kunlunyun@troila.com
  name: Kunlunyun
name: redis
version: 0.3.5
