---

monitoring:
  prometheusReplica: 2
  prometheusMemoryRequest: 400Mi
  prometheusVolumeSize: 20Gi
  prometheus:
    limits:
      cpu: 8
      memory: 32Gi
    requests:
      cpu: 80m
      memory: 400Mi
  node_exporter:
    limits:
      cpu: 600m
      memory: 500Mi
    requests:
      cpu: 51m
      memory: 180Mi
  kube_rbac_proxy:
    limits:
      cpu: 1
      memory: 100Mi
    requests:
      cpu: 10m
      memory: 20Mi
  kube_state_metrics:
    limits:
      cpu: 4
      memory: 8Gi
    requests:
      cpu: 50m
      memory: 150Mi
  alertmanager:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 20m
      memory: 30Mi
  grafana:
    enable: false
