kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kunlun-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: general
  volumeMode: Filesystem
