kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kunlun-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: general
  volumeMode: Filesystem
