kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: redis
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  serviceName: {{ .Values.service.redis_name }}
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: container-9944a4
          image: "{{ .Values.image.repository }}/redis:{{ .Values.image.tag }}"
          ports:
            - name: http-0
              containerPort: 6379
              protocol: TCP
          volumeMounts:
            - mountPath: /data/conf/redis.conf
              name: config
              subPath: redis.conf
            - mountPath: /data/
              name: kunlun
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
          - redis-server
          args:
          - /data/conf/redis.conf
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      serviceAccountName: {{ .Values.serviceAccountName }}
      serviceAccount: {{ .Values.serviceAccountName }}
      volumes:
      - name: config
        configMap:
          defaultMode: 420
          name: kunlun-configmap
      - name: kunlun
        persistentVolumeClaim:
          claimName: kunlun-pvc
  
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: mysql
  namespace: {{ .Release.Namespace }}
spec:
  serviceName: {{ .Values.service.mysql_name }}
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: "{{ .Values.image.repository }}/mysql:{{ .Values.image.tag }}"
          ports:
            - name: http-0
              containerPort: 3306
              protocol: TCP
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: '123456'
          resources: {}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          readinessProbe:
            exec:
              command:
              - /bin/bash
              - -ec
              - |
                mysql -uroot -p123456 -e"set GLOBAL max_connections =10000"
                mysqladmin status -uroot -p123456
            failureThreshold: 5
            initialDelaySeconds: 30
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 30
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      serviceAccountName: {{ .Values.serviceAccountName }}
      serviceAccount: {{ .Values.serviceAccountName }}
